version: '3.8'
services:
  tabbyapi:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - DO_PULL=true
    ports:
      - "5000:5000"
    environment:
      - NAME=TabbyAPI
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/app/models
# Example bind mount to allow for a easily editable config from the host
#      - ../config.yml:/app/config.yml 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
